changelog:
  exclude:
    labels:
      - "Épica"
    authors:
      - renovate
      - dependabot

  categories:
    - title: "Features"
      labels:
        - "Funcionalidad"

    - title: "Fixes"
      labels:
        - "Bug"
        - "Fix"

    - title: "Maintenance"
      labels:
        - "Test"
        - "Tarea Tecnica"

    - title: "Other Changes"
      labels:
        - "*"
